//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 7/09/2009 12:51:13 PM
namespace TimesheetSystem.Web.Model
{
    
    /// <summary>
    /// There are no comments for TimesheetsEntities in the schema.
    /// </summary>
    public partial class TimesheetsEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new TimesheetsEntities object using the connection string found in the 'TimesheetsEntities' section of the application configuration file.
        /// </summary>
        public TimesheetsEntities() : 
                base("name=TimesheetsEntities", "TimesheetsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new TimesheetsEntities object.
        /// </summary>
        public TimesheetsEntities(string connectionString) : 
                base(connectionString, "TimesheetsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new TimesheetsEntities object.
        /// </summary>
        public TimesheetsEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "TimesheetsEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Client in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Client> Client
        {
            get
            {
                if ((this._Client == null))
                {
                    this._Client = base.CreateQuery<Client>("[Client]");
                }
                return this._Client;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Client> _Client;
        /// <summary>
        /// There are no comments for Timesheet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Timesheet> Timesheet
        {
            get
            {
                if ((this._Timesheet == null))
                {
                    this._Timesheet = base.CreateQuery<Timesheet>("[Timesheet]");
                }
                return this._Timesheet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Timesheet> _Timesheet;
        /// <summary>
        /// There are no comments for Client in the schema.
        /// </summary>
        public void AddToClient(Client client)
        {
            base.AddObject("Client", client);
        }
        /// <summary>
        /// There are no comments for Timesheet in the schema.
        /// </summary>
        public void AddToTimesheet(Timesheet timesheet)
        {
            base.AddObject("Timesheet", timesheet);
        }
    }
    /// <summary>
    /// There are no comments for TimesheetsModel.Client in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TimesheetsModel", Name="Client")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Client : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Client object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="hourlyRate">Initial value of HourlyRate.</param>
        public static Client CreateClient(int id, string description, double hourlyRate)
        {
            Client client = new Client();
            client.id = id;
            client.Description = description;
            client.HourlyRate = hourlyRate;
            return client;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property HourlyRate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double HourlyRate
        {
            get
            {
                return this._HourlyRate;
            }
            set
            {
                this.OnHourlyRateChanging(value);
                this.ReportPropertyChanging("HourlyRate");
                this._HourlyRate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("HourlyRate");
                this.OnHourlyRateChanged();
            }
        }
        private double _HourlyRate;
        partial void OnHourlyRateChanging(double value);
        partial void OnHourlyRateChanged();
    }
    /// <summary>
    /// There are no comments for TimesheetsModel.Timesheet in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TimesheetsModel", Name="Timesheet")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Timesheet : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Timesheet object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        /// <param name="client">Initial value of Client.</param>
        /// <param name="hourlyRate">Initial value of HourlyRate.</param>
        /// <param name="quantity">Initial value of Quantity.</param>
        /// <param name="invoiced">Initial value of Invoiced.</param>
        /// <param name="dateEntered">Initial value of DateEntered.</param>
        public static Timesheet CreateTimesheet(int id, string client, double hourlyRate, double quantity, bool invoiced, global::System.DateTime dateEntered)
        {
            Timesheet timesheet = new Timesheet();
            timesheet.id = id;
            timesheet.Client = client;
            timesheet.HourlyRate = hourlyRate;
            timesheet.Quantity = quantity;
            timesheet.Invoiced = invoiced;
            timesheet.DateEntered = dateEntered;
            return timesheet;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property Client in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Client
        {
            get
            {
                return this._Client;
            }
            set
            {
                this.OnClientChanging(value);
                this.ReportPropertyChanging("Client");
                this._Client = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Client");
                this.OnClientChanged();
            }
        }
        private string _Client;
        partial void OnClientChanging(string value);
        partial void OnClientChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property HourlyRate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double HourlyRate
        {
            get
            {
                return this._HourlyRate;
            }
            set
            {
                this.OnHourlyRateChanging(value);
                this.ReportPropertyChanging("HourlyRate");
                this._HourlyRate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("HourlyRate");
                this.OnHourlyRateChanged();
            }
        }
        private double _HourlyRate;
        partial void OnHourlyRateChanging(double value);
        partial void OnHourlyRateChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this.ReportPropertyChanging("Quantity");
                this._Quantity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Quantity");
                this.OnQuantityChanged();
            }
        }
        private double _Quantity;
        partial void OnQuantityChanging(double value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Property Invoiced in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Invoiced
        {
            get
            {
                return this._Invoiced;
            }
            set
            {
                this.OnInvoicedChanging(value);
                this.ReportPropertyChanging("Invoiced");
                this._Invoiced = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Invoiced");
                this.OnInvoicedChanged();
            }
        }
        private bool _Invoiced;
        partial void OnInvoicedChanging(bool value);
        partial void OnInvoicedChanged();
        /// <summary>
        /// There are no comments for Property InvoiceNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> InvoiceNumber
        {
            get
            {
                return this._InvoiceNumber;
            }
            set
            {
                this.OnInvoiceNumberChanging(value);
                this.ReportPropertyChanging("InvoiceNumber");
                this._InvoiceNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("InvoiceNumber");
                this.OnInvoiceNumberChanged();
            }
        }
        private global::System.Nullable<short> _InvoiceNumber;
        partial void OnInvoiceNumberChanging(global::System.Nullable<short> value);
        partial void OnInvoiceNumberChanged();
        /// <summary>
        /// There are no comments for Property DateEntered in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime DateEntered
        {
            get
            {
                return this._DateEntered;
            }
            set
            {
                this.OnDateEnteredChanging(value);
                this.ReportPropertyChanging("DateEntered");
                this._DateEntered = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateEntered");
                this.OnDateEnteredChanged();
            }
        }
        private global::System.DateTime _DateEntered;
        partial void OnDateEnteredChanging(global::System.DateTime value);
        partial void OnDateEnteredChanged();
    }
}
