//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MediaCatalogueModel", "FK_Media_Item_Media_Type", "Media_Type", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MediaLibrary.WCF.Media_Type), "Media_Item", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MediaLibrary.WCF.Media_Item))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MediaCatalogueModel", "FK_Music_Track_Media_Item", "Media_Item", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MediaLibrary.WCF.Media_Item), "Music_Track", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MediaLibrary.WCF.Music_Track))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MediaCatalogueModel", "FK_Music_Track_Music_Artist", "Music_Artist", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MediaLibrary.WCF.Music_Artist), "Music_Track", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MediaLibrary.WCF.Music_Track))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MediaCatalogueModel", "FK_Music_Genre_Music_Genre", "Music_Genre", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MediaLibrary.WCF.Music_Genre), "Music_Genre1", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MediaLibrary.WCF.Music_Genre))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MediaCatalogueModel", "FK_Music_Track_Music_Genre", "Music_Genre", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MediaLibrary.WCF.Music_Genre), "Music_Track", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MediaLibrary.WCF.Music_Track))]

// Original file name:
// Generation date: 23/03/2010 8:13:43 PM
namespace MediaLibrary.WCF
{
    
    /// <summary>
    /// There are no comments for MediaCatalogueEntities in the schema.
    /// </summary>
    public partial class MediaCatalogueEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new MediaCatalogueEntities object using the connection string found in the 'MediaCatalogueEntities' section of the application configuration file.
        /// </summary>
        public MediaCatalogueEntities() : 
                base("name=MediaCatalogueEntities", "MediaCatalogueEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MediaCatalogueEntities object.
        /// </summary>
        public MediaCatalogueEntities(string connectionString) : 
                base(connectionString, "MediaCatalogueEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MediaCatalogueEntities object.
        /// </summary>
        public MediaCatalogueEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "MediaCatalogueEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Media_Item in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Media_Item> Media_Item
        {
            get
            {
                if ((this._Media_Item == null))
                {
                    this._Media_Item = base.CreateQuery<Media_Item>("[Media_Item]");
                }
                return this._Media_Item;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Media_Item> _Media_Item;
        /// <summary>
        /// There are no comments for Media_Type in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Media_Type> Media_Type
        {
            get
            {
                if ((this._Media_Type == null))
                {
                    this._Media_Type = base.CreateQuery<Media_Type>("[Media_Type]");
                }
                return this._Media_Type;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Media_Type> _Media_Type;
        /// <summary>
        /// There are no comments for Music_Artist in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Music_Artist> Music_Artist
        {
            get
            {
                if ((this._Music_Artist == null))
                {
                    this._Music_Artist = base.CreateQuery<Music_Artist>("[Music_Artist]");
                }
                return this._Music_Artist;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Music_Artist> _Music_Artist;
        /// <summary>
        /// There are no comments for Music_Genre in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Music_Genre> Music_Genre
        {
            get
            {
                if ((this._Music_Genre == null))
                {
                    this._Music_Genre = base.CreateQuery<Music_Genre>("[Music_Genre]");
                }
                return this._Music_Genre;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Music_Genre> _Music_Genre;
        /// <summary>
        /// There are no comments for Music_Track in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Music_Track> Music_Track
        {
            get
            {
                if ((this._Music_Track == null))
                {
                    this._Music_Track = base.CreateQuery<Music_Track>("[Music_Track]");
                }
                return this._Music_Track;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Music_Track> _Music_Track;
        /// <summary>
        /// There are no comments for Media_Item in the schema.
        /// </summary>
        public void AddToMedia_Item(Media_Item media_Item)
        {
            base.AddObject("Media_Item", media_Item);
        }
        /// <summary>
        /// There are no comments for Media_Type in the schema.
        /// </summary>
        public void AddToMedia_Type(Media_Type media_Type)
        {
            base.AddObject("Media_Type", media_Type);
        }
        /// <summary>
        /// There are no comments for Music_Artist in the schema.
        /// </summary>
        public void AddToMusic_Artist(Music_Artist music_Artist)
        {
            base.AddObject("Music_Artist", music_Artist);
        }
        /// <summary>
        /// There are no comments for Music_Genre in the schema.
        /// </summary>
        public void AddToMusic_Genre(Music_Genre music_Genre)
        {
            base.AddObject("Music_Genre", music_Genre);
        }
        /// <summary>
        /// There are no comments for Music_Track in the schema.
        /// </summary>
        public void AddToMusic_Track(Music_Track music_Track)
        {
            base.AddObject("Music_Track", music_Track);
        }
    }
    /// <summary>
    /// There are no comments for MediaCatalogueModel.Media_Item in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MediaCatalogueModel", Name="Media_Item")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Media_Item : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Media_Item object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        public static Media_Item CreateMedia_Item(global::System.Guid id)
        {
            Media_Item media_Item = new Media_Item();
            media_Item.id = id;
            return media_Item;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Media_File_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> Media_File_id
        {
            get
            {
                return this._Media_File_id;
            }
            set
            {
                this.OnMedia_File_idChanging(value);
                this.ReportPropertyChanging("Media_File_id");
                this._Media_File_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Media_File_id");
                this.OnMedia_File_idChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _Media_File_id;
        partial void OnMedia_File_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnMedia_File_idChanged();
        /// <summary>
        /// There are no comments for Media_Type in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MediaCatalogueModel", "FK_Media_Item_Media_Type", "Media_Type")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Media_Type Media_Type
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Media_Type>("MediaCatalogueModel.FK_Media_Item_Media_Type", "Media_Type").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Media_Type>("MediaCatalogueModel.FK_Media_Item_Media_Type", "Media_Type").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Media_Type in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Media_Type> Media_TypeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Media_Type>("MediaCatalogueModel.FK_Media_Item_Media_Type", "Media_Type");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Media_Type>("MediaCatalogueModel.FK_Media_Item_Media_Type", "Media_Type", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Music_Track in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MediaCatalogueModel", "FK_Music_Track_Media_Item", "Music_Track")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Music_Track> Music_Track
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Music_Track>("MediaCatalogueModel.FK_Music_Track_Media_Item", "Music_Track");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Music_Track>("MediaCatalogueModel.FK_Music_Track_Media_Item", "Music_Track", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MediaCatalogueModel.Media_Type in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MediaCatalogueModel", Name="Media_Type")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Media_Type : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Media_Type object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        /// <param name="description">Initial value of Description.</param>
        public static Media_Type CreateMedia_Type(global::System.Guid id, string description)
        {
            Media_Type media_Type = new Media_Type();
            media_Type.id = id;
            media_Type.Description = description;
            return media_Type;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Media_Item in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MediaCatalogueModel", "FK_Media_Item_Media_Type", "Media_Item")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Media_Item> Media_Item
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Media_Item>("MediaCatalogueModel.FK_Media_Item_Media_Type", "Media_Item");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Media_Item>("MediaCatalogueModel.FK_Media_Item_Media_Type", "Media_Item", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MediaCatalogueModel.Music_Artist in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MediaCatalogueModel", Name="Music_Artist")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Music_Artist : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Music_Artist object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Music_Artist CreateMusic_Artist(global::System.Guid id, string name)
        {
            Music_Artist music_Artist = new Music_Artist();
            music_Artist.id = id;
            music_Artist.Name = name;
            return music_Artist;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Music_Track in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MediaCatalogueModel", "FK_Music_Track_Music_Artist", "Music_Track")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Music_Track> Music_Track
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Music_Track>("MediaCatalogueModel.FK_Music_Track_Music_Artist", "Music_Track");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Music_Track>("MediaCatalogueModel.FK_Music_Track_Music_Artist", "Music_Track", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MediaCatalogueModel.Music_Genre in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MediaCatalogueModel", Name="Music_Genre")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Music_Genre : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Music_Genre object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        /// <param name="description">Initial value of Description.</param>
        public static Music_Genre CreateMusic_Genre(global::System.Guid id, string description)
        {
            Music_Genre music_Genre = new Music_Genre();
            music_Genre.id = id;
            music_Genre.Description = description;
            return music_Genre;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Music_Genre1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MediaCatalogueModel", "FK_Music_Genre_Music_Genre", "Music_Genre1")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Music_Genre> Music_Genre1
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Music_Genre>("MediaCatalogueModel.FK_Music_Genre_Music_Genre", "Music_Genre1");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Music_Genre>("MediaCatalogueModel.FK_Music_Genre_Music_Genre", "Music_Genre1", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Music_Genre2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MediaCatalogueModel", "FK_Music_Genre_Music_Genre", "Music_Genre")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Music_Genre Music_Genre2
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Music_Genre>("MediaCatalogueModel.FK_Music_Genre_Music_Genre", "Music_Genre").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Music_Genre>("MediaCatalogueModel.FK_Music_Genre_Music_Genre", "Music_Genre").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Music_Genre2 in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Music_Genre> Music_Genre2Reference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Music_Genre>("MediaCatalogueModel.FK_Music_Genre_Music_Genre", "Music_Genre");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Music_Genre>("MediaCatalogueModel.FK_Music_Genre_Music_Genre", "Music_Genre", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Music_Track in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MediaCatalogueModel", "FK_Music_Track_Music_Genre", "Music_Track")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Music_Track> Music_Track
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Music_Track>("MediaCatalogueModel.FK_Music_Track_Music_Genre", "Music_Track");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Music_Track>("MediaCatalogueModel.FK_Music_Track_Music_Genre", "Music_Track", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MediaCatalogueModel.Music_Track in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MediaCatalogueModel", Name="Music_Track")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Music_Track : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Music_Track object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        public static Music_Track CreateMusic_Track(global::System.Guid id)
        {
            Music_Track music_Track = new Music_Track();
            music_Track.id = id;
            return music_Track;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property Duration in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Duration
        {
            get
            {
                return this._Duration;
            }
            set
            {
                this.OnDurationChanging(value);
                this.ReportPropertyChanging("Duration");
                this._Duration = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Duration");
                this.OnDurationChanged();
            }
        }
        private global::System.Nullable<int> _Duration;
        partial void OnDurationChanging(global::System.Nullable<int> value);
        partial void OnDurationChanged();
        /// <summary>
        /// There are no comments for Media_Item in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MediaCatalogueModel", "FK_Music_Track_Media_Item", "Media_Item")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Media_Item Media_Item
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Media_Item>("MediaCatalogueModel.FK_Music_Track_Media_Item", "Media_Item").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Media_Item>("MediaCatalogueModel.FK_Music_Track_Media_Item", "Media_Item").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Media_Item in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Media_Item> Media_ItemReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Media_Item>("MediaCatalogueModel.FK_Music_Track_Media_Item", "Media_Item");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Media_Item>("MediaCatalogueModel.FK_Music_Track_Media_Item", "Media_Item", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Music_Artist in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MediaCatalogueModel", "FK_Music_Track_Music_Artist", "Music_Artist")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Music_Artist Music_Artist
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Music_Artist>("MediaCatalogueModel.FK_Music_Track_Music_Artist", "Music_Artist").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Music_Artist>("MediaCatalogueModel.FK_Music_Track_Music_Artist", "Music_Artist").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Music_Artist in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Music_Artist> Music_ArtistReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Music_Artist>("MediaCatalogueModel.FK_Music_Track_Music_Artist", "Music_Artist");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Music_Artist>("MediaCatalogueModel.FK_Music_Track_Music_Artist", "Music_Artist", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Music_Genre in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MediaCatalogueModel", "FK_Music_Track_Music_Genre", "Music_Genre")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Music_Genre Music_Genre
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Music_Genre>("MediaCatalogueModel.FK_Music_Track_Music_Genre", "Music_Genre").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Music_Genre>("MediaCatalogueModel.FK_Music_Track_Music_Genre", "Music_Genre").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Music_Genre in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Music_Genre> Music_GenreReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Music_Genre>("MediaCatalogueModel.FK_Music_Track_Music_Genre", "Music_Genre");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Music_Genre>("MediaCatalogueModel.FK_Music_Track_Music_Genre", "Music_Genre", value);
                }
            }
        }
    }
}
